# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39e8882086f8c02a0d65d401eee94ebf7d73b1ac35df9889a1a70227a181cfbd010100a60a5d9997b5ba50aec98ffb4b876d9b656a12b0ca95cb248ea7c70bc9

test:
  secret_key_base: 353813f8517008d62ee5f39bb8272cc86ed00c695cb6de1710a05ef1b452ef296a66f0ffa939a0be063dfb706edfc7124e006102534fd97392d772dad7228987

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
